/**
 * medical_terms.js — Dictionary of common medical terms with simple definitions.
 * Used to add hover tooltips in bot responses.
 */
const MEDICAL_TERMS = {
    "hypertension": "High blood pressure — when the force of blood against artery walls is consistently too high.",
    "diabetes": "A condition where your body can't properly process blood sugar (glucose).",
    "insulin": "A hormone made by the pancreas that helps move glucose from blood into cells for energy.",
    "cholesterol": "A waxy substance in your blood. High levels can increase risk of heart disease.",
    "anemia": "A condition where you don't have enough healthy red blood cells to carry oxygen.",
    "inflammation": "The body's natural response to injury or infection — causes redness, swelling, and pain.",
    "antibiotic": "A medicine that fights bacterial infections. Does NOT work against viruses.",
    "antiviral": "A medicine used to treat viral infections like flu or HIV.",
    "benign": "Not cancerous. A benign tumor does not spread to other parts of the body.",
    "malignant": "Cancerous. A malignant tumor can invade nearby tissues and spread.",
    "biopsy": "A procedure where a small sample of tissue is taken for testing.",
    "chronic": "A condition lasting 3 months or longer, often requiring ongoing management.",
    "acute": "A condition that comes on suddenly and is often severe but short-lived.",
    "prognosis": "The likely course and outcome of a disease or condition.",
    "symptom": "A sign of a disease or condition that you can feel, like pain or fatigue.",
    "diagnosis": "The identification of a disease based on symptoms and test results.",
    "metabolism": "The chemical processes in your body that convert food into energy.",
    "immune system": "Your body's defense network that fights infections and diseases.",
    "vaccine": "A substance that trains your immune system to recognize and fight a specific disease.",
    "hemoglobin": "A protein in red blood cells that carries oxygen throughout your body.",
    "platelet": "Tiny blood cells that help your body form clots to stop bleeding.",
    "glucose": "Blood sugar — the main type of sugar found in your blood, used for energy.",
    "bmi": "Body Mass Index — a measure of body fat based on height and weight.",
    "ecg": "Electrocardiogram — a test that records the electrical activity of your heart.",
    "mri": "Magnetic Resonance Imaging — a scan that uses magnets to create detailed body images.",
    "ct scan": "Computed Tomography — an X-ray technique that creates cross-section images of the body.",
    "iv": "Intravenous — delivered directly into a vein, usually through a needle.",
    "thyroid": "A butterfly-shaped gland in the neck that controls metabolism and energy.",
    "obesity": "A condition of excess body fat that increases the risk of health problems.",
    "asthma": "A condition where airways narrow, swell, and produce extra mucus, making breathing difficult.",
    "allergy": "An immune system reaction to a normally harmless substance like pollen or food.",
    "arthritis": "Inflammation of one or more joints, causing pain and stiffness.",
    "osteoporosis": "A condition where bones become weak and brittle, increasing fracture risk.",
    "pneumonia": "An infection that inflames the air sacs in one or both lungs.",
    "bronchitis": "Inflammation of the lining of the bronchial tubes that carry air to the lungs.",
    "eczema": "A condition that makes skin red, inflamed, and itchy. Also called dermatitis.",
    "migraine": "A severe headache often accompanied by nausea, vomiting, and sensitivity to light.",
    "vertigo": "A sensation of dizziness and spinning, often caused by inner ear problems.",
    "ultrasound": "An imaging test that uses sound waves to create pictures of organs inside the body.",
    "ibuprofen": "A common NSAID pain reliever that reduces inflammation, pain, and fever.",
    "paracetamol": "Also known as acetaminophen. A common medicine for pain relief and fever reduction.",
    "aspirin": "A medicine used to reduce pain, fever, and inflammation. Also used as a blood thinner.",
    "prediabetes": "Blood sugar levels higher than normal but not high enough for a diabetes diagnosis.",
    "a1c": "A blood test measuring average blood sugar levels over the past 2-3 months.",
};
